server:
  port: 8080
  servlet:
    context-path: /


spring:
  mvc:
    view:
      #prefix의 기준은 /src/main/webapp의 기준이다
      prefix: /WEB-INF/view/  # 변경가능
      suffix: .jsp
      
      
---

server:
  port: 8081
  servlet:
    context-path: /


spring:
  mvc:
    view:
      #prefix의 기준은 /src/main/webapp의 기준이다
      prefix: /WEB-INF/view/  # 변경가능
      suffix: .jsp
      
      
  datasource:
    url: jdbc:mysql://ljy-db.c60dwjop3klp.ap-northeast-1.rds.amazonaws.com:3306/THIRD_DB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: LJY_Amazon
    password: dl!wjd2duf
    
---
    
mybatis:
  type-aliases-package: com.ljy.third.dao
  mapper-locations: 
    - classpath:mybatis/mapper/*.xml
    
---
pageContext:
  request:
    contextPath:
