
server:
  port: 8081
  servlet:
    context-path: /  
    session:
      timeout: 10 #초단위로 세션을 설정


spring:
  #main: 
     #allow-bean-definition-overriding: true      #Spring boot 2.1 부터는 Bean Overriding이 불가능해서 해당하는 설정값을 추가
  mvc:
    view:
      #prefix의 기준은 /src/main/webapp의 기준이다
      prefix: /WEB-INF/view/  # 변경가능
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

      
      
  datasource:
    url: jdbc:mysql://ljy-db.c60dwjop3klp.ap-northeast-1.rds.amazonaws.com:3306/THIRD_DB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: LJY_Amazon
    password: dl!wjd2duf    
    
---
    
mybatis:
  type-aliases-package: com.ljy.third.dao
  mapper-locations: 
    - classpath:mybatis/mapper/*.xml


  
